### ISSUE TITLE
The display of weapon slots in the ship's characteristics is broken

### ISSUE THREAD

**Issue by Kipyatochkov** [PavelZinchenko/event-horizon-main#181]
Отображается только один слот этого типа, а если в слоте несколько типов, то этот слот в характеристиках делится на несколько. Прикрепляю несколько скриншотов.
Only one slot of this type is displayed, and if there are several types in the slot, then this slot is divided into several in the characteristics. I'm attaching some screenshots.
![Снимок экрана (270)](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/376351a7-5e98-4d03-a978-f39cd0f13d78)
![Снимок экрана (271)](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/32822a7c-4a1b-41cd-9920-d77bcab8b939)
![Снимок экрана (272)](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/2b2c6d1b-3660-4799-b437-f171473bb863)
![Снимок экрана (273)](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/620414a8-f271-4395-91ed-0c58ad424c97)
![Снимок экрана (274)](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/0d0bf595-75d0-45a7-9f7a-ad962eb3b7e8)
![Снимок экрана (275)](https://github.com/PavelZinchenko/event-horizon-main/assets/65084389/a9623d19-fe96-4941-a501-88f2df02e20c)

**Comment by CrispyToken** [comment]
The info panel only displaying one instance of a specific slot type was an intentional change a while back that aimed to resolve the issue of the weapon slots display stretching out vertically on ships with many barrels.

While this is more visually pleasing, it is kindof misleading.
Maybe displaying the number of a specific weapon group after that weapon group icon would solve this issue?
As follows: [C] X 3, [T] X 2

Multi-type slots being displayed as different single-type slots does seem like a bug to me however.
