### ISSUE TITLE
[BUG] Something is wrong with advanced ammo explosion that leave an AoE with long lifetime

### ISSUE THREAD

**Issue by Neuron114** [PavelZinchenko/event-horizon-main#338]
https://github.com/PavelZinchenko/event-horizon-main/assets/81498439/b0bdd097-a13f-435c-af82-417a7ff67901

from the video, there's something wrong with the explosion

hope this get fixed

**Comment by Inedilarion** [comment]
The problem is that destroyable projectiles that have a “push” effect throw clouds (with zero mass) back at huge speed. In vanilla it is an acid and plasma missiles.

https://github.com/PavelZinchenko/event-horizon-main/assets/66635560/a639985b-633d-464a-a634-ed8c99d990f3


https://github.com/PavelZinchenko/event-horizon-main/assets/66635560/63158618-87a8-4913-9ae7-059b138517ad
