### ISSUE TITLE
[BUG] something funny occured in pirate cannon

### ISSUE THREAD

**Issue by Neuron114** [PavelZinchenko/event-horizon-main#353]
https://github.com/PavelZinchenko/event-horizon-main/assets/81498439/96c14840-218e-4768-8ac0-3d1a00c1203e

The jorm says "weeeeeeee"

**Comment by 1distilledwater** [comment]
This bug exists in game version 1.11.2 build1677.

**Comment by Neuron114** [comment]
> This bug exists in game version 1.11.2 build1677.

it was in build 1676
I'm not aware of build 1677, maybe I should check the latest

**Comment by Neuron114** [comment]
> > This bug exists in game version 1.11.2 build1677.
> 
> it was in build 1676 I'm not aware of build 1677, maybe I should check the latest

no actually, it's still 1676 in the latest post

**Comment by 1distilledwater** [comment]
> > > This bug exists in game version 1.11.2 build1677.
> > 
> > 
> > it was in build 1676 I'm not aware of build 1677, maybe I should check the latest
> 
> no actually, it's still 1676 in the latest post

1677 is only a PC version

**Comment by JVDP-LNS** [comment]
![image](https://github.com/PavelZinchenko/event-horizon-main/assets/112297738/8d1689fd-1942-4825-bde0-4324e2c00556)

The issue seems to arise due to Visual Effects of the Smoke and SmokeAdditive types
These effects dont properly appear in game when played and throw Exceptions, which i have shown in the attached image.
