### ISSUE TITLE
Shall I add a scientist and a module upgrade system to EH?

### ISSUE THREAD

**Issue by PavelZinchenko** [PavelZinchenko/event-horizon-main#370]

**Comment by Zen9890** [comment]
I feel like this system is unnecessary in a base game for a few reasons:
1) Enemies do not scale infinitely unlike in frontier
2) Making full-gold builds in EH is much harder than in EHF because you need a lot of tech to get components, or a lot of luck and encounter grind
3) Modders (me included) most likely will demand flexible customization of scientist to tailor it how they see fit, adding extra work on top of just porting it to the EH somehow
And for pros:
1) Resources can finally find a use beyond redundant-ish faction quests in a base game
2) Scientist can be implemented in an interesting ways via quests, also expanding underused mechanics of quests in vanilla

**Comment by Neuron114** [comment]
I think about EH scientist selling alien tech points with credits or convert modules just to get 1 tech points (the amount of modules converted depends on the module rarity and where it came from), or an alternative way to get blueprint in EH aside from exploring planet


about the upgrading module, I don't think EH need that at the moment.

**Comment by qianyexiangling** [comment]
A scientist system is not necessary because the maximum strength of enemies in the game is fixed. The function of engineers synthesizing parts is necessary. Because in the game, players will hoard a large amount of low-quality equipment in the later stages. And high-quality equipment, its cost is also very high. This can facilitate players to obtain high-quality equipment.

**Comment by AnFyng** [comment]
This is a good idea. When we obtain high-quality equipment, the applicability of low-quality items is greatly reduced, and there will be a large amount of low-quality equipment remaining in the warehouse. I think it is acceptable to combine two or three low-quality equipment into high-quality equipment

**Comment by Neuron114** [comment]
actually, about me saying that EH don't need upgrade at the moment

level 300 priest xxx is really damn impossible without neutronium cutter, level 300 thunder manage to instakilled my level 200 scarab with 2900 HP if both heavy plasma emitter hits me, wormship level 300 is not hard if you have overboosted antimatter torpedo or black hole assist with other weapon, I haven't encounter any level 300 xxx capitalship enemy yet so.... I think I want that upgrade

**Comment by Tree3324417** [comment]
> level 300 priest xxx is really damn impossible without neutronium cutter, level 300 thunder xxx manage to instakilled my level 200 scarab with 2900 HP if both heavy plasma emitter hits me, wormship xxx level 300 is not hard if you have overboosted antimatter torpedo or black hole assist with other weapon + fast speed, I haven't encounter any level 300 xxx capitalship enemy yet so.... I think I want that upgrade

holy shit how many times will peoples go with asking to buff things because 'this is too strong i cant beat it'...!???!?
the ENEMY being TOO STRONG is THEIR problem, with THEIR build, THAT is what need to be addressed (flatten them out or nerf them to be comparable with other 3vets), these DO NOT imply anything on the scene of implementing the scientist module upgrade system from frontier

regarding my stance, im absolutely against anything regarding the scientist NPC in the main event horizon game itself. the two game dont even play the same way out in level strength scaling, and now we are already eating many painful strength scaling problems because on that side of the game peoples do not even have a vision on balance at all, and just go with 'whatever benefits them'.
